### ISSUE TITLE
Production with Unicorn

### ISSUE THREAD

**Issue by yhoshino11** [yhoshino11/Facebook_like_website#8]

**Comment by kRITZCREEK** [comment]
Don't! He's going to put dicks all over your facebook

**Comment by yhoshino11** [comment]
Thanks! I mean [This Unicorn](https://github.com/defunkt/unicorn)
It is a ruby library which manages processes on the production server.

I posted my schedule on [Open Space](http://frost.kritzcreek.me/instance/0), by the way. :)

**Comment by kRITZCREEK** [comment]
Allright I guess I can close this then!

**Comment by yhoshino11** [comment]
Use Puma instead of Unicorn.
Moved #59
